# Configuración para desplegar en Render.com
services:
  # Backend
  - type: web
    name: trivial-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
    
  # Frontend
  - type: web
    name: trivial-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    plan: free
